### ISSUE TITLE
Error when running Paper version git-Paper-366 

### ISSUE THREAD

**Issue by Scot-Survivor** [Nephyrin/WorldGenerationControl#2]
Just went to install the plugin. And it was disabled on the load of the server.
[11:59:37 ERROR]: Error occurred while enabling WorldGenerationControl v2.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at net.pointysoftware.worldgenerationcontrol.WorldGenerationControl.statusMsg(WorldGenerationControl.java:743) ~[?:?]
        at net.pointysoftware.worldgenerationcontrol.WorldGenerationControl.statusMsg(WorldGenerationControl.java:756) ~[?:?]
        at net.pointysoftware.worldgenerationcontrol.WorldGenerationControl.onEnable(WorldGenerationControl.java:692) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-366]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-366]        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-366]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-366]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

It has 2G memory attached and 512M minimum. This was on the load of the server.

**Comment by MdBourg98** [comment]
Last update was 8 years ago. I'm assuming its long dead.
